# Generated by cpp11: do not edit by hand

loglike_cpp11 <- function(params, data, misc) {
  .Call(`_genecastR_loglike_cpp11`, params, data, misc)
}

logprior_cpp11 <- function(params, misc) {
  .Call(`_genecastR_logprior_cpp11`, params, misc)
}
